export const AksilMenu = [
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/assiete03.jpg",
    price: "7.79$",
    category: ["assiettes"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/assiete01.jpg",
    price: "7.79$",
    category: ["assiettes"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/assiete02.jpg",
    price: "7.79$",
    category: ["assiettes"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/burger01.jpg",
    price: "7.79$",
    category: ["burger"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/burger02.jpg",
    price: "7.79$",
    category: ["burger"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/burger03.jpg",
    price: "7.79$",
    category: ["burger"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/pizza01.jpg",
    price: "7.79$",
    category: ["pizza"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/pizza02.jpg",
    price: "7.79$",
    category: ["pizza"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/pizza03.jpg",
    price: "7.79$",
    category: ["pizza"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/sandwiche01.jpg",
    price: "7.79$",
    category: ["sandwiches"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/sandwiche02.jpg",
    price: "7.79$",
    category: ["sandwiches"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/sandwiche03.jpg",
    price: "7.79$",
    category: ["sandwiches"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/panini01.jpg",
    price: "7.79$",
    category: ["paninis"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/panini02.jpg",
    price: "7.79$",
    category: ["paninis"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/panini03.jpg",
    price: "7.79$",
    category: ["paninis"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/tacos01.jpg",
    price: "7.79$",
    category: ["tacos"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/tacos02.jpg",
    price: "7.79$",
    category: ["tacos"],
  },
  {
    title: "Burger au poivre",
    description: "Super Burger au poivre à venir tester",
    imgPath: "./menu/tacos03.jpg",
    price: "7.79$",
    category: ["tacos"],
  },
];
